# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SideApps' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Alamofire'
pod 'RxSwift', '~> 5'
pod 'RxCocoa', '~> 5'
pod 'Swinject'
  # Pods for SideApps

  target 'SideAppsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
